# Generated by Django 5.1 on 2024-08-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leetcodequestion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="leetcodequestion",
            name="url",
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="completion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="todolist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="leetscraper.todolist",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="list_description",
            field=models.CharField(default="Default list for tasks.", max_length=200),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="list_name",
            field=models.CharField(default="To Do List", max_length=30),
        ),
    ]

