# Generated by Django 5.1 on 2024-08-31 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0002_remove_leetcodequestion_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="list_description",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="list_name",
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="body",
            field=models.TextField(default="No Body Provided"),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="code_stubs",
            field=models.TextField(blank=True, default="No code_stubs provided"),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="companies",
            field=models.TextField(blank=True, default="No companies provided"),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="hints",
            field=models.TextField(blank=True, default="No hints provided"),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="is_paid_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="similar_questions",
            field=models.TextField(blank=True, default="No similar questions provided"),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="title_slug",
            field=models.CharField(default="No title slug provided", max_length=225),
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="topics",
            field=models.TextField(blank=True, default="No topics provided"),
        ),
        migrations.AddField(
            model_name="todolist",
            name="name",
            field=models.CharField(default="To Code List", max_length=30),
        ),
        migrations.AddField(
            model_name="todolist",
            name="user",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leetcodequestion",
            name="difficulty",
            field=models.CharField(default="No difficulty provided", max_length=50),
        ),
        migrations.AlterField(
            model_name="leetcodequestion",
            name="question_title",
            field=models.CharField(default="No question provided", max_length=225),
        ),
    ]
