# Generated by Django 5.1 on 2024-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0007_alter_codesolution_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="user",
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(default="Shared To-Do List", max_length=30),
        ),
    ]
