# Generated by Django 5.1 on 2024-09-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0009_todolist_user_alter_todolist_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leetcodequestion",
            name="todolist",
        ),
        migrations.DeleteModel(
            name="ToDoList",
        ),
    ]
