# Generated by Django 5.1 on 2024-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0010_remove_leetcodequestion_todolist_delete_todolist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leetcodequestion",
            name="hints",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="leetcodequestion",
            name="topics",
            field=models.JSONField(default=list),
        ),
    ]
