# Generated by Django 5.1 on 2024-09-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0011_alter_leetcodequestion_hints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnotes",
            name="body",
            field=models.TextField(blank=True, default="Click to add"),
        ),
        migrations.AlterField(
            model_name="questionnotes",
            name="title",
            field=models.CharField(default="Untitled", max_length=50),
        ),
    ]
