# Generated by Django 5.1 on 2024-09-30 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leetscraper", "0012_alter_questionnotes_body_alter_questionnotes_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leetcodequestion",
            name="completion",
        ),
        migrations.AddField(
            model_name="leetcodequestion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
